import { ReactNode } from 'react';
import Header from './Header';
import Footer from './Footer';
import Head from "next/head";

const MainLayout = ({ children }: { children?: ReactNode }) => {
  return <div>
    <Head>
      <title>Smoky Chat</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    {children}
    <Footer />
  </div>
}

export default MainLayout;
